grobidHome: ../grobid-home

tmpPath: ../grobid-home/tmp/

#------------------------------------------------------
#proxy to be used for external call ("null" when no proxy)
proxyHost: null
proxyPort: null

# entity-fishing server information for performing entity disambiguation
# for https, indicate 443 as port
entityFishingHost: cloud.science-miner.com/nerd
entityFishingPort: 443
#entityFishingHost: localhost
#entityFishingPort: 8090

# sequence labelling algorithm to be used, for CRF select wapiti, for deep learning select delft
#engine: wapiti
engine: delft

# additional info for DeLFT only (for embeddings default is glove, could be elmo or flair)
delftInstall: ../../delft
#delftArchitecture: BidLSTM_CRF
#delftArchitecture: BidLSTM_CRF-with-ELMo
delftArchitecture: scibert
delftEmbeddings: glove

corpusPath: resources/dataset/software/corpus
templatePath: resources/dataset/software/crfpp-templates/software.template
